experiment: "experiment_2"

data_dir: "testdata/experiment2/data"
data_frames: "testdata/experiment2/dac-train.xlsx"

TransformerClass: "RopeCondDACTransformer" 
vocab_size: 1024
num_tokens: 8

cond_params: 1 #1 (not counting the classes)
model_size: 512 # must be divisible by num_heads

Ti: 86 # 172 #86
Tt: 430 # must match the length of the sequences in the batch
batch_size: 4  #**


num_layers: 2 #**
num_heads: 4 #8 # 8 # embed_size must be divisible by num_heads
forward_expansion: 2 #4 #4
dropout_rate: 0.2
learning_rate: 0.0005

num_epochs: 300 ### 800 

ErrorLogRate: 10 #2 ### 10
checkpoint_interval: 300 ###50 # 25

